version: '3.8'

services:
  webapi:
    image: profilesapi
    build:
      context: .
      dockerfile: ProfilesApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MsSql#2024Secure!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
