# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./innoClinic
      run: dotnet restore innoClinic.sln
    - name: Build
      working-directory: ./innoClinic
      run: dotnet build --no-restore innoClinic.sln
    - name: Display dotnet version
      run: dotnet --version
    - name: UnitTests
      working-directory: ./innoClinic
      run: dotnet test Services.UnitTests/Services.UnitTests.csproj --no-build --verbosity normal --results-directory "TestResults-unit"
    - name: IntegrationTests
      working-directory: ./innoClinic
      run: dotnet test Offices.IntegrationTests/Offices.IntegrationTests.csproj --no-build --verbosity normal --results-directory "TestResults-integration"
    # - name: Upload dotnet test results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: dotnet-results
    #     path: ./innoClinic/TestResults-unit
          # Use always() to always run this step to publish test results when there are test failures
          # if: ${{ always() }}
